common:
  nameOverride: ""
  fullnameOverride: ""
  awsAccount: "1234567890"
  awsRegion: ap-northeast-2

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

workload:
  kind: Deployment
  replicaCount: 1
  image:
    ecr:
      enabled: false
      repository: ""
    repository: ""
    pullPolicy: IfNotPresent
    tag: "0.1.0"
  containerPort: 80
  imagePullSecrets: []
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  probes:
    livenessProbe:
      path: /
      conditions: {}
    readinessProbe:
      path: /
      conditions: {}
  resources: {}
  databaseHost: ""
  deployStage: ""
  nodeSelector: {}
  tolerations: []
  affinity: {}

service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http

ingress:
  enabled: false
  className: ""
  scheme: internet-facing
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80