common:
  nameOverride: fastcampus-app
  fullnameOverride: fastcampus-app

serviceAccount:
  create: true

workload:
  kind: Deployment
  replicaCount: 1
  image:
    ecr:
      enabled: true
      repository: fastcampus-app-image
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 512Mi
  containerPort: 8000
  probes:
    livenessProbe:
      path: /lectures/
      conditions:
        initialDelaySeconds: 20
        timeoutSeconds: 15
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
    readinessProbe:
      path: /lectures/
      conditions:
        initialDelaySeconds: 20
        timeoutSeconds: 15
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
  deployStage: prod

autoscaling:
  enabled: false

service:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http

ingress:
  enabled: true
  className: alb
  hosts:
    - paths:
        - path: /
          pathType: Prefix
