apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
spec:
  containers:
  - name: temp-container
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /mnt/kafka-volume
      name: kafka-data
  volumes:
  - name: kafka-data
    persistentVolumeClaim:
      claimName: data-kafka-controller-0
