apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastcampus-case1
  labels:
    app.kubernetes.io/name: fastcampus-case1
    app.kubernetes.io/instance: fastcampus-case1-prod
automountServiceAccountToken: true