apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-service
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
