apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastcampus-case1-dev
  labels:
    app.kubernetes.io/name: fastcampus-case1-dev
    app.kubernetes.io/instance: fastcampus-case1-dev
automountServiceAccountToken: true