name: Deploy

on:
  release:
    types:
      - published

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"

      - name: Build and Push Container Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: fastcampus-app-image
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          docker build -t $REGISTRY/$IMAGE_NAME:$SHA_SHORT .
          docker push $REGISTRY/$IMAGE_NAME:$SHA_SHORT

      - uses: azure/setup-kubectl@v3

      - name: Create kube-config
        run: |
          aws eks --region ap-northeast-2 update-kubeconfig --name fastcampus-infra-cluster

      - name: Apply Kubernetes manifests
        run: |
          export ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
          export IMAGE_TAG="$(git rev-parse --short HEAD)"
          export DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          envsubst < manifests/prod/deployment.yaml > temp.yaml && mv temp.yaml manifests/prod/deployment.yaml
          envsubst < manifests/dev/deployment.yaml > temp.yaml && mv temp.yaml manifests/dev/deployment.yaml
          kubectl apply -f manifests -R
